# Generated by Django 5.0.1 on 2024-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_sum',
            field=models.FloatField(default=0),
        ),
    ]
